### ISSUE TITLE
APIのステータスを保持するための状態変数

### ISSUE THREAD

**Issue by Takoyaki-neonz-net** [Takoyaki-neonz-net/EarthRadar#5]
[Reception.tsx](https://github.com/Takoyaki-neonz-net/EarthRadar/blob/main/earthdev/src/components/Reception.tsx)5~28行目の文を書き直し

# 工程
APIのステータスを保持するための状態変数
ローカルストレージからデータを取得
JSON.parseでオブジェクトに変換、存在しない場合は null を返す
exportJma は Obj or null が入る
exportJma が変更されたらローカルストレージに保存
その際に JSON.stringify で文字列に変換して保存

**Comment by minagishl** [comment]
On this page.
https://vercel.com/guides/react-context-state-management-nextjs

**Comment by Takoyaki-neonz-net** [comment]
#b7803bdb9ffde9ecf9e6e537e100d194850f93ac
このコミットで適応させましたので閉じます。
